# Generated by Django 6.0.6 on 2026-07-01 08:41

import django.utils.timezone
import djfractions.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredients',
            name='quantity',
            field=djfractions.models.fields.DecimalFractionField(coerce_thirds=True, decimal_places=3, default=1, limit_denominator=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Litre'), ('pc', 'Piece'), ('ml', 'Mililitre'), ('cups', 'Cups')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredients',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
