# Generated by Django 6.0.6 on 2026-07-01 08:51

import djfractions.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_ingredients_amount_ingredients_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=djfractions.models.fields.DecimalFractionField(coerce_thirds=True, decimal_places=3, limit_denominator=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Litre'), ('pc', 'Piece'), ('ml', 'Mililitre'), ('cups', 'Cups')], max_length=20),
        ),
    ]
